name = "MonteCarloFramework"
uuid = "14a022ff-64fe-4055-afb2-58b44d5ca93b"
authors = ["Qi Yang <qiyang@mail.ustc.edu.cn> and contributors"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.7"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
